fitness_app/fit/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = "fit"

urlpatterns = [
                  path("", views.index, name="index"),
                  path("login", views.login_get, name="login"),
                  path("signup", views.signup_get, name="signup"),
                  path("logout", views.logout_get, name="logout"),
                  path("signup_post", views.Signup, name="signup_post"),
                  path("login_post", views.Login, name="login_post"),
                  path("add_task/<int:id>", views.Add_task, name="add_task"),
                  path("calories", views.Calories, name="calories")
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fitness_app/fitness_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from fit.views import *

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('' , include('fit.urls'))
              ] 


  

fitness_app/fit/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


options = [
    ['breakfast', 'breakfast'],
    ['lunch', 'lunch'],
    ['dinner', 'dinner'],
    ['Miscellaneous', 'Miscellaneous'],
]


class User_details(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    mobile_no = models.IntegerField(null=True)
    profile_image = models.FileField(null=True)
    age = models.IntegerField(null=True)
    gender = models.CharField(max_length=100, null=True)
    heigth = models.CharField(max_length=100, null=True)
    weight = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.user.first_name


class Goals(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    Task_date = models.DateField(null=True)
    Due_date = models.DateField(null=True)
    task_name = models.CharField(null=True, max_length=500)

    def __str__(self):
        return self.task_name


class Food_details(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    category = models.CharField(max_length=500, choices=options)
    food_type = models.CharField(max_length=500, null=True)
    calorie = models.DecimalField(max_digits=5, decimal_places=2, default=0, blank=True)
    quantity = models.IntegerField(default=1, null=True, blank=True)

    def __str__(self):
        return self.food_type

fitness_app/fit/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from .models import *
from django.contrib.auth.models import User


def index(request):
    return render(request, 'fit/home.html', {'text': "Hello "})


def login_get(request):
    return render(request, 'fit/login.html')


def signup_get(request):
    return render(request, 'fit/signup.html')


def logout_get(request):
    logout(request)
    print(User.first_name, "logged out")
    return render(request, 'fit/home.html')


def Signup(request):
    if request.method == "POST":
        dic = request.POST
        u = dic['uname']
        p = dic['con_pass']
        mob = dic['pno']
        f = dic['fname']
        l = dic['lname']
        email = dic['email']
        age = dic['age']
        gender = dic['gender']
        img = request.FILES['pic']
        weight = dic['weight']
        height = dic['height']
        userdata = User.objects.filter(username=u)
        if userdata:
            messages.error(request, 'User Already Exists')
            return render(request, 'fit/login.html')
        else:
            user = User.objects.create_user(first_name=f, last_name=l, username=u, password=p, email=email)
            User_details.objects.create(user=user, mobile_no=mob, profile_image=img, age=age, gender=gender,
                                        weight=weight, heigth=height)
            return render(request, 'fit/login.html')
    return render(request, 'fit/signup.html')


def Login(request):
    if request.method == "POST":
        dic = request.POST
        u = dic['username']
        p = dic['pass']
        user = authenticate(username=u, password=p)
        if user:
            login(request, user)
            return render(request, 'fit/main_page.html')
        else:
            messages.error(request, 'User not found')
            context = {
                "message": "User not found"
            }
            return render(request, 'fit/login.html', context)

    return render(request, 'fit/login.html')


def Add_task(request, id):
    task = Goals.objects.filter(user=request.user)
    if request.method == "POST":
        dic = request.POST
        tasks = dic["title"]
        date = dic["task_date"]
        due_date = dic["due_date"]
        Goals.objects.create(user=request.user, task_name=tasks, Due_date=due_date, Task_date=date)
    d = {"task": task}
    return render(request, 'fit/add_task.html', d)


def Calories(request):
    food = Food_details.objects.filter(user=request.user)
    return render(request,'fit/calculate_calories.html')

fitness_app/fit/templates/fit/add_task.html
<!DOCTYPE html>
{% load static %}


<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ADD TASK</title>
    <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
     <form  action="" method="post" >
            {% csrf_token %}
            <div class="form-group">
              <input type="text" class="form-control" name="title"  placeholder="Add Task">
            </div>
            <div class="form-group">
                <h5>Date</h5>
              <input type="date" class="form-control" name="task_date" value="Date">
            </div>

            <div class="form-group">
                <h5>Due Date</h5>
              <input type="date" class="form-control" name="due_date" value="Due Date">
            </div>
            <div class="text-center">
              <button type="submit" class="btn btn-primary" >ADD</button>
            </div>
          </form>

<div class="container">
  <h2>Daily Task To Be Completed</h2>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Task Name</th>
        <th>Date </th>
        <th>Due Date</th>
      </tr>
    </thead>
    <tbody>
      <tr>
          {% for i in task %}
        <td>{{i.task_name}}</td>
        <td>{{ i.Task_date}}</td>
        <td>{{ i.Due_date}}</td>
      </tr>
    {% endfor %}

    </tbody>
  </table>
      <div class="text-left">
         <a href="{% url 'fit:calories' %}">View Calories </a>
      </div>
</div>
</body>
</html>

fitness_app/fit/templates/fit/calculate_calories.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Calories</title>
</head>
<body>
<center>
<select class="browser-default custom-select">
  <option selected>SELECT</option>
    <option value="3">Breakfast</option>
</select>

    </center>
</body>

</html>

fitness_app/fit/templates/fit/home.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>
        {% block title %}
        HOME
        {% endblock title %}
    </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <link rel="stylesheet" href="{% static 'fit/home.css' %}">
    <script src="{% static 'fit/home.js' %}"></script>
    <script src="{% static 'fit/paralaxx.min.js' %}"></script>
</head>
<body>  

{% block nav %}
    <header>
        <nav>
            <div class="menu-icon">
                <i class="fa fa-bars fa-2x"></i>
            </div>
            <div class="logo">
                {% block heading %}
                   FITNESS FREAKS
                {% endblock heading %}
            </div>
            <div class="menu">
                <ul>
                {% block login %}
                    <li><a href="{% url 'fit:login' %}">LOGIN</a></li>
                {% endblock login %}
                {% block signup  %}
                     <li><a href="{% url 'fit:signup' %}">SIGNUP</a></li>
                {% endblock signup %}

                {% if user.is_authenticated %}
                    {% block logout %}
                        <li><a href="{% url 'fit:logout' %}">LOGOUT</a></li>
                        <li><a href="{% url 'fit:add_task' request.user.id %}">ADD TASK</a></li>
                    {% endblock logout %}
                {% endif %}
                
                </ul>
            </div>
        </nav>
    </header>
{% endblock nav %}
{% block main %}

    <div class="container">
        <p class="middle-text">
            WORK HARD
        </p>
        <div class="parallax-window" data-parallax="scroll" data-z-index="1" data-image-src="{% static 'fit/active-young-woman-training-outdoor.jpg' %}">
            <p class="info">
                PASSION
            </p>
        </div>
        <p class="middle-text">
            YOU HAVE IT IN YOU
        </p>
        <div class="parallax-window" data-parallax="scroll" data-z-index="1" data-image-src="{% static 'fit/sports-731506_1920.jpg' %}">
            <p class="info">
                EXERCISE
            </p>
        </div>
        <p class="middle-text">
            RUN FARTHER, RUN BETTER
        </p>
        <div class="parallax-window" data-parallax="scroll" data-z-index="1" data-image-src="{% static 'fit/strong-man-training-gym.jpg' %}">
            <p class="info">
                IGNITE YOUR INNER POTENTIAL 
            </p>
        </div>
        <p class="middle-text">
            SHAPE YOUR BODY, SHAPE YOUR LIFE
        </p>
        <div class="parallax-window" data-parallax="scroll" data-z-index="1" data-image-src="{% static 'fit/fitness-elements-with-space-top.jpg' %}">
            <p class="info">
                DREAM
            </p>
        </div>
        <p class="middle-text">
            ALL PROGRESS TAKES PLACE OUTSIDE YOUR COMFORT ZONE
        </p>
        <div class="parallax-window" data-parallax="scroll" data-z-index="1" data-image-src="{% static 'fit/yoga-2587066_1920.jpg' %}">
            <p class="info">
                JOIN TO TRANSFORM
           </p>
    </div>
    {% endblock main %}
    <div class="content">
        {% block content %}
        {% endblock content %}
    </div>
</body>
<footer>
<hr>
    <div class="foot">
        <div class="text" id="join">
           <p>JOIN US</p>
        </div>
        <div class="text">
            <h4>Made By</h4>
            <p>ManojKumar</p>
            <p>Sumedha</p>
        </div>
    </div>
</footer>
</html> 

fitness_app/fit/templates/fit/login.html
{% extends './home.html' %}

{% block title %}
        LOGIN
{% endblock title %}

{% block login %}
{% endblock login %}

{% block main %}
{% endblock main %}

{% block content %}
    <form method="post" class="frm" action="{% url 'fit:login_post' %}">
        {% csrf_token %}
        <div class="frm-text">
            <p>Username</p>
            <input type="text" name="username" id="username" placeholder="Username">
        </div>
        <div class="frm-text">
            <p>Password</p>
            <input type="password" name="pass" id="pass" placeholder="Enter your password">
        </div>
        <div id="button">
            <input type="submit" value="LOGIN">
        </div>
    </form>
{% endblock content %}

fitness_app/fit/templates/fit/main_page.html
{% extends './home.html' %}

{% block login %}
{% endblock login %}

{% block signup %}
{% endblock signup %}

{% block main %}
{% endblock main %}

{% block content %}
    logged in 
{% endblock content %}

fitness_app/fit/templates/fit/signup.html
{% extends './home.html' %}

{% block title %}
    SIGNUP
{% endblock title %}

{% block signup  %}
{% endblock signup  %}

{% block main %}
{% endblock main %}

{% block content %}
     <form action="{% url 'fit:signup_post' %}" method="post" enctype="multipart/form-data" class="frm">
            {% csrf_token %}
                <h2>SIGNUP</h2>
              <div class="frm-text">
                  <p>First Name</p>
                  <input type="text" name="fname"  placeholder="First Name">
              </div>

              <div class="frm-text">
                <p>Last Name</p>
                <input type="text" name="lname"  placeholder="Last Name">
              </div>

              <div class="frm-text">
                <p>Phone number</p>
                <input type="number" name="pno"  placeholder="Phone number">
              </div>


              <div class="frm-text">
                <p>Profile picture</p>
                <input type="file" name="pic"  placeholder="Choose a picture">
              </div>


              <div class="frm-text">
                <p>Email</p>
                <input type="email" name="email"  placeholder="Your Email">
              </div>


              <div class="frm-text">
                <p>Username</p>
                <input type="text" name="uname"  placeholder="Enter Username">
              </div>
              <div class="frm-text">
                <p>Password</p>
                <input type="text" name="pass"  placeholder="Enter Password">
              </div>
              <div class="frm-text">
                <p>Confirm Password</p>
                <input type="password" name="con_pass"  placeholder="Confirm Password">
              </div>
              <div class="frm-text">
                <p>Age</p>
                <input type="number" name="age"  placeholder="Your Age">
              </div>
              <div class="frm-text">
                <p>Gender</p>
               <select name="gender" id="gender" class="gen">
                   <option  value="female">Female</option>
                   <option value="male">Male</option>
                   <option value="other">Other</option>
               </select>
              </div>
              <div class="frm-text">
                <p>Height</p>
                <input type="number" name="height"  placeholder="Your height(in cms)">
              </div>
              <div class="frm-text">
                <p>Weight</p>
                <input type="number" name="weight"  placeholder="Your Weight">
              </div>
             <div>
                 <input type="submit" value="Submit">
             </div>

          </form>

{% endblock content %}